/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SomeThing } from "./SomeThing";
import { SomeThingCountArgs } from "./SomeThingCountArgs";
import { SomeThingFindManyArgs } from "./SomeThingFindManyArgs";
import { SomeThingFindUniqueArgs } from "./SomeThingFindUniqueArgs";
import { DeleteSomeThingArgs } from "./DeleteSomeThingArgs";
import { SomeThingService } from "../someThing.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => SomeThing)
export class SomeThingResolverBase {
  constructor(
    protected readonly service: SomeThingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "SomeThing",
    action: "read",
    possession: "any",
  })
  async _someThingsMeta(
    @graphql.Args() args: SomeThingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [SomeThing])
  @nestAccessControl.UseRoles({
    resource: "SomeThing",
    action: "read",
    possession: "any",
  })
  async someThings(
    @graphql.Args() args: SomeThingFindManyArgs
  ): Promise<SomeThing[]> {
    return this.service.someThings(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => SomeThing, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SomeThing",
    action: "read",
    possession: "own",
  })
  async someThing(
    @graphql.Args() args: SomeThingFindUniqueArgs
  ): Promise<SomeThing | null> {
    const result = await this.service.someThing(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SomeThing)
  @nestAccessControl.UseRoles({
    resource: "SomeThing",
    action: "delete",
    possession: "any",
  })
  async deleteSomeThing(
    @graphql.Args() args: DeleteSomeThingArgs
  ): Promise<SomeThing | null> {
    try {
      return await this.service.deleteSomeThing(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
