{{- if .Values.traefik.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.traefik.middleware.redirect }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}