name: amplication-server

deployment:
  replicaCount: 1
  volume:
    name: amplication-server-artifacts-data
    path: /artifacts
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  podAnnotations: {}
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  image:
    pullPolicy: Always
    repository: 407256539111.dkr.ecr.us-east-1.amazonaws.com/amplication-prod-server
    tag: 0.0.3
    imagePullSecrets: []

service:
  type: ClusterIP
  port: 
    target: 3000
  protocol: TCP
secrets: 
  gcp: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiYW1wbGljYXRpb24tcHJvZHVjdGlvbiIsCiAgInByaXZhdGVfa2V5X2lkIjogIjgyMzQ2NTFmMmVlNGU4MjYwODNjZTI1ZTkwOTdiZTIwNDI4Y2RkNDMiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRFAxc1k2Z3lKZmZRSE5cbi8zTldjVHZlMFUyaEU3ZnpBL0c2bGRNeG1jYjZhR3JrVkc4YVNuTUdzVEYyUnZzQk1XTjJ3QU9hM1BMMm5sTitcbnk3N1RabUpqUGErcldHVGZIclQ3cFgrQjBJd3k0cXhaeWVOZi9SK0VWRkNzYUhsdktyQm9uckMvK201bVNydEpcbmxEMUdEYU53UUhQNlhqaDA3OWtnTEtnYjhSOXJzdVExSytGOUhEYWlKRDlvc0xRdUJmaGxzVDhDdVJSYnk1QVlcblJkb0d6MExNUW5XWTN5c2JNSmZDZGs4VmdpRG1ES2tkZ2NKWnA5MjBPQTZiTWozMVhCWjU2NW5WS000ZUJnZ2JcbmpDK3p1Q2xQZTR4SHVTL1hVZXAraWsxVFNiQzM4c0t6V2RGZjhhTDBFcjJBbjNDeFNoTFZ1cm8rWjNNWWRTWnRcbnRQc1NKRG9QQWdNQkFBRUNnZ0VBVFJNQkpPNi9YdmpkSS9iZzMwUVRwMEFvRVIxZVlIVHNmanlVZXJianRyWGxcbk9mSmoxelNYcm5va2RRL0Nnb0U5dU9waEM5dDNFR1RMWXVDTXpobVFUK3d1eXBSM3A5UmIybHhYeWh5NytSemRcblBGamxoSkc2VDlqeXA5VUFmMnl0eWNaYmxuMzQxZDlOeiszMHdSZEtybFNBamU3RjhmdUdJZXZkbGFzWDgxaFNcbnM0OHYxOEEvSEkydjVPTndFOWgyVGJZd0ZIUHRmSncvempBZVExV2tKcXc0V1crZmlETGVEcjFkQ3RMQ1o3ZVBcbnowZ2YzU2xPd21sUGl1WEg5ZVBlK2RsaEg3T2VyZWlsSjdsTmNLby94bW9LSE1CbHBHOFVSblF2QXBORTh4b3Fcbk9nZUYyRUZVQVJscDRhbGNHbllzYVNQMDVxSVVYNTJjQlJHTHVhcFpsUUtCZ1FENWh1LzVaeXVkVnc5c1BOY2dcbjZ3OTRGdnA0SVY5bzJETm5ndFpzNHlydlU3RGxjTzFNWUVWcCtBaGhWUlBENU1pQm5wUkRVZW1KbmxNNVN5b2tcbmlJWm04T3Q0bDM4Z3RzVWI5cExneHllbDBId05WeWcxUWJ2aEQwRVpwemwrVFk1UXp6ZTYzNFhuSWhKSkh0WEZcbmxiQ0NxMHBrQm4wMmxleUQwc3htQ09qWG13S0JnUURWT3Y1c2ZmSkJCbVVQRHZsa1ZQN3FkajJxVXBSanI1c2ZcbjVPLzNlRzAvS2hja21qdXdXbXJiaDA1Rnp6amdrc3FuNFJtc0NXYVROSG9mM3gxaU9GZk5PMkFzbXdvVXN3M2pcbkc2eGF0M1ZEby9qeG1wcEdseDNLTjhFRDNQK3cxRHM4Q1ducFlPM2g1Ty9CQnlacHFQZHU5Z1BpUW9XN05FNmhcbm1PZ093NGdBblFLQmdRRG5VZXVYeHNnTkJZOTdwTzgrU2dzK0pmY3VkS214VlhSYUNsWGovYmhvdzZvakdjd3lcbjJMQ2c2MXBCZVJCb3N1Z2FHYnVTcVJZYUNSZFg3dEZ6cXNrR0YyUURtRlkzS3BpU01zUzQ4b2RUMVhHYklHaGFcbjdzUlFnTWEyRkd0ZEptSy9rVW8xeUUrbkZOUGt5MXdiM29nU3F0NjgyYk1zYmxJalpzRXIraWg0N3dLQmdIOGVcbjk1VjRsSmQ5bDN3ZHdrSzFoWEFFWkFrSnlGdVIwcHAySXpYVy90SmNab1cweVliK3NKd0dFM3o4Nkh6Q0pyMWxcbkxxZm94dFZWd01VRmdBQVJkUTd1cWd5TnRiblhjWjBHMzM4SnhvZzMxbTg3YTJSUUxUdGtkOWEweDE4RmQvYjNcbjZjTnZ2UUlpT1dsTHVQUGUvdnlSQUluQWZQZTVYSE5zdEZRdzhBRGxBb0dCQU5EamNMU0RTL292emNKclMyM09cbkVqcFdhZUFtd0ViNVNwVWozZGhLVGtqeno3TnBEV09EbEhCd3crcGpGT1VpUFNHQmZXY3ZlZitKOHNPSXVxVXFcblFaM3U4WkpVV3NQMWhuUTFHYzNGcDRhTWovbys4YmxMc0J3bk80NzZvM0dPY0hyd25rbjFLY2txaXVJM2U5VVdcbkRqZjdJQ09zaytveVdXem9jYTFkcFBkS1xuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImF3cy1wcm9kLWFjY2Vzcy05NjNAYW1wbGljYXRpb24tcHJvZHVjdGlvbi5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMDE4NTk2NTA2NjA3MzI0NTk2MDAiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2F3cy1wcm9kLWFjY2Vzcy05NjMlNDBhbXBsaWNhdGlvbi1wcm9kdWN0aW9uLmlhbS5nc2VydmljZWFjY291bnQuY29tIgp9Cg==
ingress:
  enabled: true
  hostname: server.amplication-dev.com

config:
  env:
    BCRYPT_SALT_OR_ROUNDS: "10"
    CONTAINER_BUILDER_DEFAULT: docker
    CORS_ENABLE: "1"
    DEFAULT_DISK: local
    DOCKER_HOST: tcp://docker:2375
    GITHUB_APP_APP_ID: "189214"
    GITHUB_APP_AUTH_SCOPE: user:email,repo,read:org
    GITHUB_APP_CLIENT_ID: Iv1.7eb319d8e3c170d7
    GITHUB_APP_CLIENT_SECRET: 3a387bd802276f83b89e26135b10b6f4b580694c
    GITHUB_APP_INSTALLATION_URL: https://github.com/apps/amplication-aws/installations/new?state={state}
    GITHUB_APP_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEA+s4zfEdw3yVBVeHDOSCJ1ecctVIB+NH0XbtxcSoT4HsfTVH4\nSsKd/jffRmYJdA0M3vgSers/EyW+x46E4+bNGjbK6Ego/tM5CuekT/RM8OjfMLC8\nmxgfamQ9bAbF+BIc0S1pKlWzk6ORzKIrkN7Q30Jny8w7NOIcHeHccCvpSgIkKyz5\nkFM69uNPV0vtibRD6stzZ+TNKvAYRhBy2J5nubMSDe+GR0IYhTQgrwp+DowChWo2\nGrJrHGB3ptty0QqnlEoBFPaNB5UFtia2g9eP0/kvzjcMd5dqNFMfOXaaCoF5M41O\ncp1vCAiFniOLv40X/Q/lOAdqcJGDAGIG/b7BAQIDAQABAoIBAQCdSHDbMEYlekyV\n2iW+jpxB61SClTItYyVXHrSOni+m6C+CIrSN1ayU/17i3BxzjbeToIieNQziKhqR\nNNw7u8LF/LSUpKQo4jd0kj3l8jPKJI/LDhrJPIB/DOvD8h92aY1u1IaOCP67yKkn\nZk/h4wmj6RYEpUg/6shtKPY/1hnP0XgjWm4O0sUYbFQaFun1+etpEdSzQb3ku0qU\nJi5VKGSN3JIb39Nl/y0hbNiQKuxyE6cDfwfXX3NpgW0gucG3GuCib7xGBM9g5jmM\nYz37u+4Rx1ZaEZrq/ECxdf2WN+kVe2y7xERmoqfmjZw5ciweBmtx7+AtQrRyVzQW\nuI4eCDEdAoGBAP2QexLA2F2cwkGoZCqRXUUDyf8M4mSsOje1SxzANp3YSC1eZYVq\nDgmbtMOaOcbSA8FSfGhwiVuJ/5RCq7ZBF4aPJEe3F8I8IX0tGFxrRlb/ANC7fMCL\nVr5OaXnPTUTFGcPX7SMgYVcdi1sBiprCcNHwo4kMsWOwOKr7y7+fJOozAoGBAP02\n76iAZ9YDZVMh5whSqlEZNwyQPQ7m/JdvmPCxjmDRFa7Ceag6fUvh94sYBScZv+pM\nldfwlpvyGTCqaVA8rbjvEelxTC5T2N/He6dYsaaS5euxg56lCw/JMYCDfCNAO2OE\nBRNj+vxrpCXm/6ukPWuzJJvru96+Oz3ZCxPCf1v7AoGAFDgzODmch0p6yxWMd0CE\nOX6l2urCGtkJA2w3gyFouYmHp+aBHfRpDicWcQqZVNtmZUIYnZNrwJrugHoYiz4B\njD9Z20YkZN66pOq1qJj9UO6guARbXFdAIYjLLGV1eehlt5I+XLC2UmYOuMEUtmaO\n7I7N253hf1uMCUZu5ubf4LUCgYEAluZ2TGS5fMDpUXGSzVL2TP5J4CLVQFxHi7fl\n3QrzXp873Lno5mh04xP3Ad1+tJ6T0H1zjwzBtI3ClU35FOgUX3GZqxTp4XH2fOXU\nuxYQSMSiYKOZXKHexbmQ1pWFFTziJ5w1qiibGnLLkArpstBeCiDoYENL4qJbi7Ac\n+dmfLKECgYAh4d9Mmpop2Y0uZGCeHobfLwePSTnLXX1HRAhnWJ7aHYjfnnu8NeZn\ns+PgEiSkLEORdMyyp2+eWqkbaeRbsvUkNcDQzeDSqo0xxT1vtTSYIFFMKpvc4/bT\ns9YmTPdGvf6Nqi8S4FJShorFq4po9u6TtMHUDz6cLPqOoDz3cm6t1g==\n-----END
      RSA PRIVATE KEY-----'
    GITHUB_CLIENT_SECRET: 0fff7413a35bf313637bec566b9727c7f74ffaa9
    GITHUB_CLIENT_ID: 9fa6ba1586a17f7d75ef
    GITHUB_REDIRECT_URI: https://server.amplication-dev.com/github/callback
    GITHUB_SCOPE: user:email
    GITHUB_SECRET_SECRET_NAME: projects/948093699220/secrets/github-secret-amplication-dev-aWS/versions/1
    GOOGLE_APPLICATION_CREDENTIALS: /app/packages/amplication-server/amplication-production-8234651f2ee4.json
    HOST: http://localhost:3000
    JWT_SECRET: jwt-secret
    LOCAL_DISK_ROOT: /artifacts
    NODE_ENV: production
    PORT: "3000"
    SERVICE_JWT_SECRET: service-jwt-secret
pvc:
  storageLimit: 5Gi
  storageRequest: 1Gi

# Postgresql Server
postgres:
  install: false
  postgresqlPassword: atGgu!Y81Uwb
  postgresqlUsername: postgres
  db: amplication
  domain: amplication-useast1-prod-primary.csf5nwabym5c.us-east-1.rds.amazonaws.com
  postgresqlPort: 5432
  fullnameOverride: postgresql
  postgresql:
    image: groundnuty/k8s-wait-for:v1.3
    imagePullPolicy: Always
    primary:
      podLabels: { name: "postgres" }
