# @amplication/server
name: amplication-server

replicas: 1

image:
  registry: 562551246305.dkr.ecr.us-east-1.amazonaws.com
  repository: amplication-dev-server
  tag: v1.0.0-beta

resources:
  # Example:
  # limits:
  #    cpu: 100m
  #    memory: 128Mi
  limits: {}
  # Example:
  # requests:
  #    cpu: 100m
  #    memory: 128Mi
  requests: {}

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

traefik:
  enabled: true
  # traefik.path -- The path to match for Traefik to route to service
  rule: PathPrefix(`/graphql`)
  entrypoints:
    http:
      name: web
    https:
      name: websecure
