apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.deployment.volume.name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: {{ .Values.pvc.storageRequest }}