{{- if .Values.traefik.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "traefik.names.fullname" . }}
  labels:
  {{- include "common.labels" . | nindent 4 }}
  {{- include "traefik.labels" . | nindent 4 }}
{{- end }}