# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: AWS-CD

on:
  workflow_dispatch:
    inputs:
      destination_environment:
        description: 'Name of the namespace to create'     
        required: true
        default: 'staging-os'
      source_branch_name:
        description: 'Name of the branch to use'     
        required: true
        default: 'master'
      cluster_name:
        description: 'Cluster name'     
        required: true
        default: 'amplication-useast1-prod-eks'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v2
      - name: Fetch master
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master
      